export interface Make {
  id: string
  name: string
}

export const makes: Make[] = [
  { id: "acura", name: "Acura" },
  { id: "alfa-romeo", name: "Alfa Romeo" },
  { id: "aston-martin", name: "Aston Martin" },
  { id: "audi", name: "Audi" },
  { id: "bentley", name: "Bentley" },
  { id: "bmw", name: "BMW" },
  { id: "buick", name: "Buick" },
  { id: "cadillac", name: "Cadillac" },
  { id: "chevrolet", name: "Chevrolet" },
  { id: "chrysler", name: "Chrysler" },
  { id: "dodge", name: "Dodge" },
  { id: "ferrari", name: "Ferrari" },
  { id: "fiat", name: "Fiat" },
  { id: "ford", name: "Ford" },
  { id: "genesis", name: "Genesis" },
  { id: "gmc", name: "GMC" },
  { id: "honda", name: "Honda" },
  { id: "hyundai", name: "Hyundai" },
  { id: "infiniti", name: "Infiniti" },
  { id: "jaguar", name: "Jaguar" },
  { id: "jeep", name: "Jeep" },
  { id: "kia", name: "Kia" },
  { id: "lamborghini", name: "Lamborghini" },
  { id: "land-rover", name: "Land Rover" },
  { id: "lexus", name: "Lexus" },
  { id: "lincoln", name: "Lincoln" },
  { id: "lotus", name: "Lotus" },
  { id: "lucid", name: "Lucid" },
  { id: "maserati", name: "Maserati" },
  { id: "mazda", name: "Mazda" },
  { id: "mclaren", name: "McLaren" },
  { id: "mercedes-benz", name: "Mercedes-Benz" },
  { id: "mini", name: "MINI" },
  { id: "mitsubishi", name: "Mitsubishi" },
  { id: "nissan", name: "Nissan" },
  { id: "polestar", name: "Polestar" },
  { id: "porsche", name: "Porsche" },
  { id: "ram", name: "RAM" },
  { id: "rivian", name: "Rivian" },
  { id: "rolls-royce", name: "Rolls-Royce" },
  { id: "subaru", name: "Subaru" },
  { id: "tesla", name: "Tesla" },
  { id: "toyota", name: "Toyota" },
  { id: "volkswagen", name: "Volkswagen" },
  { id: "volvo", name: "Volvo" },
]
