export interface Model {
  id: string
  name: string
  makeId: string
}

export const models: Model[] = [
  // Acura
  { id: "ilx", name: "ILX", makeId: "acura" },
  { id: "integra", name: "Integra", makeId: "acura" },
  { id: "mdx", name: "MDX", makeId: "acura" },
  { id: "nsx", name: "NSX", makeId: "acura" },
  { id: "rdx", name: "RDX", makeId: "acura" },
  { id: "tlx", name: "TLX", makeId: "acura" },

  // Audi
  { id: "a3", name: "A3", makeId: "audi" },
  { id: "a4", name: "A4", makeId: "audi" },
  { id: "a5", name: "A5", makeId: "audi" },
  { id: "a6", name: "A6", makeId: "audi" },
  { id: "a7", name: "A7", makeId: "audi" },
  { id: "a8", name: "A8", makeId: "audi" },
  { id: "e-tron", name: "e-tron", makeId: "audi" },
  { id: "e-tron-gt", name: "e-tron GT", makeId: "audi" },
  { id: "q3", name: "Q3", makeId: "audi" },
  { id: "q4-e-tron", name: "Q4 e-tron", makeId: "audi" },
  { id: "q5", name: "Q5", makeId: "audi" },
  { id: "q7", name: "Q7", makeId: "audi" },
  { id: "q8", name: "Q8", makeId: "audi" },
  { id: "r8", name: "R8", makeId: "audi" },
  { id: "rs3", name: "RS 3", makeId: "audi" },
  { id: "rs5", name: "RS 5", makeId: "audi" },
  { id: "rs6", name: "RS 6", makeId: "audi" },
  { id: "rs7", name: "RS 7", makeId: "audi" },
  { id: "s3", name: "S3", makeId: "audi" },
  { id: "s4", name: "S4", makeId: "audi" },
  { id: "s5", name: "S5", makeId: "audi" },
  { id: "tt", name: "TT", makeId: "audi" },

  // BMW
  { id: "2-series", name: "2 Series", makeId: "bmw" },
  { id: "3-series", name: "3 Series", makeId: "bmw" },
  { id: "4-series", name: "4 Series", makeId: "bmw" },
  { id: "5-series", name: "5 Series", makeId: "bmw" },
  { id: "7-series", name: "7 Series", makeId: "bmw" },
  { id: "8-series", name: "8 Series", makeId: "bmw" },
  { id: "i4", name: "i4", makeId: "bmw" },
  { id: "i5", name: "i5", makeId: "bmw" },
  { id: "i7", name: "i7", makeId: "bmw" },
  { id: "ix", name: "iX", makeId: "bmw" },
  { id: "m2", name: "M2", makeId: "bmw" },
  { id: "m3", name: "M3", makeId: "bmw" },
  { id: "m4", name: "M4", makeId: "bmw" },
  { id: "m5", name: "M5", makeId: "bmw" },
  { id: "m8", name: "M8", makeId: "bmw" },
  { id: "x1", name: "X1", makeId: "bmw" },
  { id: "x2", name: "X2", makeId: "bmw" },
  { id: "x3", name: "X3", makeId: "bmw" },
  { id: "x4", name: "X4", makeId: "bmw" },
  { id: "x5", name: "X5", makeId: "bmw" },
  { id: "x6", name: "X6", makeId: "bmw" },
  { id: "x7", name: "X7", makeId: "bmw" },
  { id: "z4", name: "Z4", makeId: "bmw" },

  // Chevrolet
  { id: "blazer", name: "Blazer", makeId: "chevrolet" },
  { id: "bolt-ev", name: "Bolt EV", makeId: "chevrolet" },
  { id: "bolt-euv", name: "Bolt EUV", makeId: "chevrolet" },
  { id: "camaro", name: "Camaro", makeId: "chevrolet" },
  { id: "colorado", name: "Colorado", makeId: "chevrolet" },
  { id: "corvette", name: "Corvette", makeId: "chevrolet" },
  { id: "equinox", name: "Equinox", makeId: "chevrolet" },
  { id: "malibu", name: "Malibu", makeId: "chevrolet" },
  { id: "silverado-1500", name: "Silverado 1500", makeId: "chevrolet" },
  { id: "silverado-2500hd", name: "Silverado 2500HD", makeId: "chevrolet" },
  { id: "silverado-3500hd", name: "Silverado 3500HD", makeId: "chevrolet" },
  { id: "suburban", name: "Suburban", makeId: "chevrolet" },
  { id: "tahoe", name: "Tahoe", makeId: "chevrolet" },
  { id: "traverse", name: "Traverse", makeId: "chevrolet" },
  { id: "trailblazer", name: "Trailblazer", makeId: "chevrolet" },
  { id: "trax", name: "Trax", makeId: "chevrolet" },

  // Dodge
  { id: "challenger", name: "Challenger", makeId: "dodge" },
  { id: "charger", name: "Charger", makeId: "dodge" },
  { id: "durango", name: "Durango", makeId: "dodge" },
  { id: "hornet", name: "Hornet", makeId: "dodge" },

  // Ford
  { id: "bronco", name: "Bronco", makeId: "ford" },
  { id: "bronco-sport", name: "Bronco Sport", makeId: "ford" },
  { id: "edge", name: "Edge", makeId: "ford" },
  { id: "escape", name: "Escape", makeId: "ford" },
  { id: "expedition", name: "Expedition", makeId: "ford" },
  { id: "explorer", name: "Explorer", makeId: "ford" },
  { id: "f-150", name: "F-150", makeId: "ford" },
  { id: "f-150-lightning", name: "F-150 Lightning", makeId: "ford" },
  { id: "f-250", name: "F-250", makeId: "ford" },
  { id: "f-350", name: "F-350", makeId: "ford" },
  { id: "maverick", name: "Maverick", makeId: "ford" },
  { id: "mustang", name: "Mustang", makeId: "ford" },
  { id: "mustang-mach-e", name: "Mustang Mach-E", makeId: "ford" },
  { id: "ranger", name: "Ranger", makeId: "ford" },

  // Honda
  { id: "accord", name: "Accord", makeId: "honda" },
  { id: "civic", name: "Civic", makeId: "honda" },
  { id: "cr-v", name: "CR-V", makeId: "honda" },
  { id: "hr-v", name: "HR-V", makeId: "honda" },
  { id: "odyssey", name: "Odyssey", makeId: "honda" },
  { id: "passport", name: "Passport", makeId: "honda" },
  { id: "pilot", name: "Pilot", makeId: "honda" },
  { id: "prologue", name: "Prologue", makeId: "honda" },
  { id: "ridgeline", name: "Ridgeline", makeId: "honda" },

  // Hyundai
  { id: "elantra", name: "Elantra", makeId: "hyundai" },
  { id: "ioniq-5", name: "IONIQ 5", makeId: "hyundai" },
  { id: "ioniq-6", name: "IONIQ 6", makeId: "hyundai" },
  { id: "kona", name: "Kona", makeId: "hyundai" },
  { id: "palisade", name: "Palisade", makeId: "hyundai" },
  { id: "santa-cruz", name: "Santa Cruz", makeId: "hyundai" },
  { id: "santa-fe", name: "Santa Fe", makeId: "hyundai" },
  { id: "sonata", name: "Sonata", makeId: "hyundai" },
  { id: "tucson", name: "Tucson", makeId: "hyundai" },
  { id: "venue", name: "Venue", makeId: "hyundai" },

  // Jeep
  { id: "compass", name: "Compass", makeId: "jeep" },
  { id: "gladiator", name: "Gladiator", makeId: "jeep" },
  { id: "grand-cherokee", name: "Grand Cherokee", makeId: "jeep" },
  { id: "grand-cherokee-l", name: "Grand Cherokee L", makeId: "jeep" },
  { id: "grand-wagoneer", name: "Grand Wagoneer", makeId: "jeep" },
  { id: "renegade", name: "Renegade", makeId: "jeep" },
  { id: "wagoneer", name: "Wagoneer", makeId: "jeep" },
  { id: "wrangler", name: "Wrangler", makeId: "jeep" },

  // Kia
  { id: "carnival", name: "Carnival", makeId: "kia" },
  { id: "ev6", name: "EV6", makeId: "kia" },
  { id: "ev9", name: "EV9", makeId: "kia" },
  { id: "forte", name: "Forte", makeId: "kia" },
  { id: "k5", name: "K5", makeId: "kia" },
  { id: "niro", name: "Niro", makeId: "kia" },
  { id: "seltos", name: "Seltos", makeId: "kia" },
  { id: "sorento", name: "Sorento", makeId: "kia" },
  { id: "soul", name: "Soul", makeId: "kia" },
  { id: "sportage", name: "Sportage", makeId: "kia" },
  { id: "stinger", name: "Stinger", makeId: "kia" },
  { id: "telluride", name: "Telluride", makeId: "kia" },

  // Lexus
  { id: "es", name: "ES", makeId: "lexus" },
  { id: "gx", name: "GX", makeId: "lexus" },
  { id: "is", name: "IS", makeId: "lexus" },
  { id: "lc", name: "LC", makeId: "lexus" },
  { id: "ls", name: "LS", makeId: "lexus" },
  { id: "lx", name: "LX", makeId: "lexus" },
  { id: "nx", name: "NX", makeId: "lexus" },
  { id: "rc", name: "RC", makeId: "lexus" },
  { id: "rx", name: "RX", makeId: "lexus" },
  { id: "rz", name: "RZ", makeId: "lexus" },
  { id: "tx", name: "TX", makeId: "lexus" },
  { id: "ux", name: "UX", makeId: "lexus" },

  // Mazda
  { id: "cx-30", name: "CX-30", makeId: "mazda" },
  { id: "cx-5", name: "CX-5", makeId: "mazda" },
  { id: "cx-50", name: "CX-50", makeId: "mazda" },
  { id: "cx-70", name: "CX-70", makeId: "mazda" },
  { id: "cx-90", name: "CX-90", makeId: "mazda" },
  { id: "mazda3", name: "Mazda3", makeId: "mazda" },
  { id: "mx-5-miata", name: "MX-5 Miata", makeId: "mazda" },

  // Mercedes-Benz
  { id: "a-class", name: "A-Class", makeId: "mercedes-benz" },
  { id: "amg-gt", name: "AMG GT", makeId: "mercedes-benz" },
  { id: "c-class", name: "C-Class", makeId: "mercedes-benz" },
  { id: "cla", name: "CLA", makeId: "mercedes-benz" },
  { id: "cle", name: "CLE", makeId: "mercedes-benz" },
  { id: "e-class", name: "E-Class", makeId: "mercedes-benz" },
  { id: "eqb", name: "EQB", makeId: "mercedes-benz" },
  { id: "eqe", name: "EQE", makeId: "mercedes-benz" },
  { id: "eqs", name: "EQS", makeId: "mercedes-benz" },
  { id: "g-class", name: "G-Class", makeId: "mercedes-benz" },
  { id: "gla", name: "GLA", makeId: "mercedes-benz" },
  { id: "glb", name: "GLB", makeId: "mercedes-benz" },
  { id: "glc", name: "GLC", makeId: "mercedes-benz" },
  { id: "gle", name: "GLE", makeId: "mercedes-benz" },
  { id: "gls", name: "GLS", makeId: "mercedes-benz" },
  { id: "maybach", name: "Maybach", makeId: "mercedes-benz" },
  { id: "s-class", name: "S-Class", makeId: "mercedes-benz" },
  { id: "sl", name: "SL", makeId: "mercedes-benz" },

  // Nissan
  { id: "altima", name: "Altima", makeId: "nissan" },
  { id: "ariya", name: "Ariya", makeId: "nissan" },
  { id: "armada", name: "Armada", makeId: "nissan" },
  { id: "frontier", name: "Frontier", makeId: "nissan" },
  { id: "kicks", name: "Kicks", makeId: "nissan" },
  { id: "leaf", name: "LEAF", makeId: "nissan" },
  { id: "maxima", name: "Maxima", makeId: "nissan" },
  { id: "murano", name: "Murano", makeId: "nissan" },
  { id: "pathfinder", name: "Pathfinder", makeId: "nissan" },
  { id: "rogue", name: "Rogue", makeId: "nissan" },
  { id: "sentra", name: "Sentra", makeId: "nissan" },
  { id: "titan", name: "Titan", makeId: "nissan" },
  { id: "versa", name: "Versa", makeId: "nissan" },
  { id: "z", name: "Z", makeId: "nissan" },

  // Porsche
  { id: "718-boxster", name: "718 Boxster", makeId: "porsche" },
  { id: "718-cayman", name: "718 Cayman", makeId: "porsche" },
  { id: "911", name: "911", makeId: "porsche" },
  { id: "cayenne", name: "Cayenne", makeId: "porsche" },
  { id: "macan", name: "Macan", makeId: "porsche" },
  { id: "panamera", name: "Panamera", makeId: "porsche" },
  { id: "taycan", name: "Taycan", makeId: "porsche" },

  // RAM
  { id: "1500", name: "1500", makeId: "ram" },
  { id: "2500", name: "2500", makeId: "ram" },
  { id: "3500", name: "3500", makeId: "ram" },
  { id: "promaster", name: "ProMaster", makeId: "ram" },

  // Subaru
  { id: "ascent", name: "Ascent", makeId: "subaru" },
  { id: "brz", name: "BRZ", makeId: "subaru" },
  { id: "crosstrek", name: "Crosstrek", makeId: "subaru" },
  { id: "forester", name: "Forester", makeId: "subaru" },
  { id: "impreza", name: "Impreza", makeId: "subaru" },
  { id: "legacy", name: "Legacy", makeId: "subaru" },
  { id: "outback", name: "Outback", makeId: "subaru" },
  { id: "solterra", name: "Solterra", makeId: "subaru" },
  { id: "wrx", name: "WRX", makeId: "subaru" },

  // Tesla
  { id: "model-3", name: "Model 3", makeId: "tesla" },
  { id: "model-s", name: "Model S", makeId: "tesla" },
  { id: "model-x", name: "Model X", makeId: "tesla" },
  { id: "model-y", name: "Model Y", makeId: "tesla" },
  { id: "cybertruck", name: "Cybertruck", makeId: "tesla" },

  // Toyota
  { id: "4runner", name: "4Runner", makeId: "toyota" },
  { id: "bz4x", name: "bZ4X", makeId: "toyota" },
  { id: "camry", name: "Camry", makeId: "toyota" },
  { id: "corolla", name: "Corolla", makeId: "toyota" },
  { id: "corolla-cross", name: "Corolla Cross", makeId: "toyota" },
  { id: "crown", name: "Crown", makeId: "toyota" },
  { id: "gr86", name: "GR86", makeId: "toyota" },
  { id: "gr-corolla", name: "GR Corolla", makeId: "toyota" },
  { id: "gr-supra", name: "GR Supra", makeId: "toyota" },
  { id: "grand-highlander", name: "Grand Highlander", makeId: "toyota" },
  { id: "highlander", name: "Highlander", makeId: "toyota" },
  { id: "land-cruiser", name: "Land Cruiser", makeId: "toyota" },
  { id: "prius", name: "Prius", makeId: "toyota" },
  { id: "rav4", name: "RAV4", makeId: "toyota" },
  { id: "sequoia", name: "Sequoia", makeId: "toyota" },
  { id: "sienna", name: "Sienna", makeId: "toyota" },
  { id: "tacoma", name: "Tacoma", makeId: "toyota" },
  { id: "tundra", name: "Tundra", makeId: "toyota" },
  { id: "venza", name: "Venza", makeId: "toyota" },

  // Volkswagen
  { id: "arteon", name: "Arteon", makeId: "volkswagen" },
  { id: "atlas", name: "Atlas", makeId: "volkswagen" },
  { id: "atlas-cross-sport", name: "Atlas Cross Sport", makeId: "volkswagen" },
  { id: "golf", name: "Golf", makeId: "volkswagen" },
  { id: "golf-gti", name: "Golf GTI", makeId: "volkswagen" },
  { id: "golf-r", name: "Golf R", makeId: "volkswagen" },
  { id: "id4", name: "ID.4", makeId: "volkswagen" },
  { id: "jetta", name: "Jetta", makeId: "volkswagen" },
  { id: "taos", name: "Taos", makeId: "volkswagen" },
  { id: "tiguan", name: "Tiguan", makeId: "volkswagen" },

  // Volvo
  { id: "c40-recharge", name: "C40 Recharge", makeId: "volvo" },
  { id: "s60", name: "S60", makeId: "volvo" },
  { id: "s90", name: "S90", makeId: "volvo" },
  { id: "v60", name: "V60", makeId: "volvo" },
  { id: "v90", name: "V90", makeId: "volvo" },
  { id: "xc40", name: "XC40", makeId: "volvo" },
  { id: "xc40-recharge", name: "XC40 Recharge", makeId: "volvo" },
  { id: "xc60", name: "XC60", makeId: "volvo" },
  { id: "xc90", name: "XC90", makeId: "volvo" },
]

export function getModelsByMake(makeId: string): Model[] {
  return models.filter((model) => model.makeId === makeId)
}
